name: Check Links

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@3c3b66f1f7d0900e37b71eca45b63ea9eedfce31 # 1.0.17
      with:
        use-quiet-mode: 'yes'
        config-file: '.github/workflows/mlc_config.json'
